"""call log

Hand written, not autogenerated. It must stay in step with
src/models/calls_model.py; tests/unit/test_calls_service.py fails if a column
is added to the model without a migration to match.

There are no cost columns here and none may be added. Free records what
happened on a call, not what it cost.

Revision ID: 0002_calls
Revises: 0001_livekit_settings
Create Date: 2026-08-09
"""

import sqlalchemy as sa
import sqlmodel
from alembic import op

revision = "0002_calls"
down_revision = "0001_livekit_settings"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "call",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uuid", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("room_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("caller", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("channel", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("agent_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("business_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_seconds", sa.Integer(), nullable=True),
        sa.Column("turn_count", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_call_uuid"), "call", ["uuid"], unique=True)
    # Unique, not merely indexed: it is what makes reporting the start of a
    # call idempotent across a worker restart.
    op.create_index(op.f("ix_call_room_name"), "call", ["room_name"], unique=True)

    op.create_table(
        "turn",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uuid", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("call_id", sa.Integer(), nullable=False),
        sa.Column("role", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("text", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("spoken_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["call_id"], ["call.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_turn_uuid"), "turn", ["uuid"], unique=True)
    op.create_index(op.f("ix_turn_call_id"), "turn", ["call_id"], unique=False)


def downgrade() -> None:
    op.drop_index(op.f("ix_turn_call_id"), table_name="turn")
    op.drop_index(op.f("ix_turn_uuid"), table_name="turn")
    op.drop_table("turn")
    op.drop_index(op.f("ix_call_room_name"), table_name="call")
    op.drop_index(op.f("ix_call_uuid"), table_name="call")
    op.drop_table("call")
